name: Compress Code

on:
  push:
    branches:
      - main

jobs:
  compress-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Compress code
        run: |
          git archive --format=zip HEAD -o myapp.zip

      - name: Upload code
        uses: actions/upload-artifact@v2
        with:
          name: myapp.zip
          path: myapp.zip
