downloadLink = "https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackConvert/main/files"
resourcePackName = "Minecraft-Mod-Language-Modpack-1-18-FabricT1-19-3-Fabric"
md5Name = "1.18-fabrict1.19.3-fabric"
