name: Package Modpack

on:
  push:
    branches:
      - 1.19.4-OptiFabric-Dev
  workflow_dispatch:

jobs:
  Build-Modpack:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
          
      - run: git config user.email "${{ github.actor }}@users.noreply.github.com"
        if: ${{ github.repository_owner != 'github-actions' }}

      - run: git config user.name "${{ github.actor }}"
        if: ${{ github.repository_owner != 'github-actions' }}   
        
      - name: Fix Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
          timezoneMacos: "Asia/Shanghai"
        
      - name: Add date and time to the file name
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      
      - name: Package Modpack
        run: |
          rm -rf .github
          rm -rf .git
          rm README.md
          zip -r "./MineOptimiz OptiFabric v1.19.4-Dev-${{ steps.date.outputs.date }}.zip" ./*
      
      - uses: actions/upload-artifact@v2
        with:
          name: MineOptimiz OptiFabric v1.19.4-Dev-${{ steps.date.outputs.date }}.zip
          path: "./MineOptimiz OptiFabric v1.19.4-Dev-${{ steps.date.outputs.date }}.zip"
     