name: Build Modpack

on:
  push:
    branches:
      - 1.17.1-dev
  workflow_dispatch:

jobs:
  Build-Modpack:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
          
      - run: git config user.email "${{ github.actor }}@users.noreply.github.com"
        if: ${{ github.repository_owner != 'github-actions' }}

      - run: git config user.name "${{ github.actor }}"
        if: ${{ github.repository_owner != 'github-actions' }}
        
      - name: Get commit hash
        id: commit-hash
        uses: pr-mpt/actions-commit-hash@v2
        with:
         prefix: v1.17.1-0.7.x-
         short: true
  
    
      
      - name: Build Modpack
        run: |
          rm -rf .github
          rm -rf .git
          rm README.md
          cd /home/runner/work/Tiao-s-Modpack-For-Tiao-s-Server/Tiao-s-Modpack-For-Tiao-s-Server/
          zip -r /home/runner/work/Tiao-s-Modpack-For-Tiao-s-Server/Tiao-s-Modpack-For-Tiao-s-Server/${{ steps.commit-hash.outputs.hash }}-${{ inputs.build_type }}-lite.mrpack-lite.mrpack ./*
      
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.commit-hash.outputs.hash }}-${{ inputs.build_type }}-lite.mrpack-lite.mrpack
          path: /home/runner/work/Tiao-s-Modpack-For-Tiao-s-Server/Tiao-s-Modpack-For-Tiao-s-Server/${{ steps.commit-hash.outputs.hash }}-${{ inputs.build_type }}-lite.mrpack-lite.mrpack
