name: Compress Code

on:
  push:
    branches:
      - 1.17.1

jobs:
  compress-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: |
          git config --global user.email "<youremail>"
          git config --global user.name "<yourname>"
          
      - run: |
          mkdir /tmp/repo
          shopt -s extglob; rsync -r --exclude='.github' --exclude='README.md' ./ /tmp/repo/
          cd /tmp/repo
          git archive --output=v1.17.1-0.7.x-unknown.zip HEAD .

      - uses: actions/upload-artifact@v2
         with:
         name: v1.17.1-0.7.x-unknown.zip
         path: /tmp/repo/v1.17.1-0.7.x-unknown.zip
