name: Compress Code

on:
  push:
    branches:
      - 1.17.1

jobs:
  compress-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup git
        run: |
          git config --global user.email "<youremail>"
          git config --global user.name "<yourname>"
          
      - name: Compress code
        run: |
          git archive --output=myapp.zip HEAD

      - name: Upload code
        uses: actions/upload-artifact@v2
        with:
          name: myapp.zip
          path: myapp.zip
