name: Build Modpack

on:
  push:
    branches:
      - 1.19.4-full
  workflow_dispatch:

env:
  ZIP_NAME: v1.19.4-0.9.x-${{ github.event.repository.updated_at }}-full.mrpack
  ZIP_PATH: ${{ github.workspace }}/${{ env.ZIP_NAME }}

jobs:
  Build-Modpack:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: modpack
      
      - uses: actions/cache@v2
        with:
          path: ${{ env.ZIP_PATH }}
          key: ${{ runner.os }}-${{ env.ZIP_NAME }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.ZIP_NAME }}-
      
      - run: git config user.email "${{ github.actor }}@users.noreply.github.com"
        if: github.event_name == 'push'
      
      - run: git config user.name "${{ github.actor }}"
        if: github.event_name == 'push'
      
      - name: Build Modpack
        working-directory: modpack
        run: |
          rm -rf .github
          rm -rf .git
          rm README.md
          zip -r ${{ env.ZIP_PATH }} ./*
      
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.ZIP_NAME }}
          release_name: ${{ env.ZIP_NAME }}
          draft: false
          prerelease: false
      
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP_PATH }}
          asset_name: ${{ env.ZIP_NAME }}
          asset_content_type: application/zip