name: Compress Code

on:
  push:
    branches:
      - 1.17.1

jobs:
  compress-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup git
        run: |
          git config --global user.email "<youremail>"
          git config --global user.name "<yourname>"
          
      - name: Compress code
        run: |
          # Filter out .github directory and README.md file
          git ls-files | grep -v -E '^((?!\.github|README\.md).)*$' | xargs git archive --format=zip --output=myapp.zip HEAD
          
      - name: Rename archive file
        run: |
          mv myapp.zip v1.17.1-0.7.x-unknown.zip
          
      - name: Upload code
        uses: actions/upload-artifact@v2
        with:
          name: v1.17.1-0.7.x-unknown.zip
          path: v1.17.1-0.7.x-unknown.zip
